//
//  GenerateMenuBoardRepositoryIMPL.swift
//  Generate_Menu_Image
//
//  Created by Carki on 11/30/25.
//

import Foundation

class GenerateMenuBoardRepositoryIMPL: GenerateMenuBoardRepository {
    let api: CodeitAPI
    
    init(api: CodeitAPI) {
        self.api = api
    }
    
    func generateMenuBoard(menus: [MenuCategory], storeID: Int) async -> Result<CodeitEmptyResponse, MenuBoardNetworkError> {
        let categoriesDTO = menus.map { mapToDTO($0) }
        return await api.generateMenuBoard(
            GenerateMenuRequestModel(
                autoGenerateDescriptions: true,
                autoGenerateImages: true,
                categories: categoriesDTO,
                storeID: storeID
            )
        )
    }
}

private extension GenerateMenuBoardRepositoryIMPL {
    
    func mapToDTO(_ category: MenuCategory) -> CategoryDTO {
        return CategoryDTO(
            categoryName: category.categoryName,
            items: category.items.map { mapToDTO($0) }
        )
    }

    func mapToDTO(_ item: MenuItem) -> ItemDTO {
        return ItemDTO(
            name: item.name,
            price: Int(item.price) ?? 0
        )
    }
}
