//
//  GenerateMenuBoardRequestModel.swift
//  Generate_Menu_Image
//
//  Created by Carki on 11/30/25.
//

import Foundation

struct GenerateMenuRequestModel: Codable {
    let autoGenerateDescriptions, autoGenerateImages: Bool
    let categories: [CategoryDTO]
    let storeID: Int

    enum CodingKeys: String, CodingKey {
        case autoGenerateDescriptions = "auto_generate_descriptions"
        case autoGenerateImages = "auto_generate_images"
        case categories
        case storeID = "store_id"
    }
}

struct CategoryDTO: Codable {
    let categoryName: String
    let items: [ItemDTO]

    enum CodingKeys: String, CodingKey {
        case categoryName = "category_name"
        case items
    }
}

// MARK: - Item
struct ItemDTO: Codable {
    let name: String
    let price: Int
}
