//
//  GenerateMenuModel.swift
//  Generate_Menu_Image
//
//  Created by Carki on 11/28/25.
//

import Foundation

struct GenerateMenuModel {
    let autoGenerateDescriptions: Bool
    let autoGenerateImages: Bool
    let categories: [MenuCategory]
    let storeID: Int
}

struct MenuCategory: Identifiable {
    let id: UUID
    var categoryName: String
    var items: [MenuItem]
    
    init(id: UUID = UUID(), categoryName: String = "", items: [MenuItem] = []) {
        self.id = id
        self.categoryName = categoryName
        self.items = items
    }
}

struct MenuItem: Identifiable {
    let id: UUID
    var name: String
    var price: String
    
    init(id: UUID = UUID(), name: String = "", price: String = "") {
        self.id = id
        self.name = name
        self.price = price
    }
}
